export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const EXPIRED_TOKEN = 'EXPIRED_TOKEN';
export const SET_ANTI_SOCIAL = 'SET_ANTI_SOCIAL';