export const LOAD_DELIVERIES_SUCCESS = 'LOAD_DELIVERIES_SUCCESS';
export const CANCEL_DELIVERIES_SUCCESS = 'CANCEL_DELIVERIES_SUCCESS';
export const LOAD_DELIVERIES_INDEX_SUCCESS = 'LOAD_DELIVERIES_INDEX_SUCCESS';
export const SUBMIT_DELIVERIES_REQUEST_SUCCESS = 'SUBMIT_DELIVERIES_REQUEST_SUCCESS';
