export const LOAD_FRACTIONALS_SUCCESS = 'LOAD_FRACTIONALS_SUCCESS';
export const BUY_SELL_FRACTIONALS_SUCCESS = 'BUY_SELL_FRACTIONALS_SUCCESS';
export const LOAD_FRACTIONALS_SHOW_SUCCESS = 'LOAD_FRACTIONALS_SHOW_SUCCESS';
export const CANCEL_FRACTIONALS_SUCCESS = 'CANCEL_FRACTIONALS_SUCCESS';
