export const LOAD_MARGIN_SUCCESS = 'LOAD_MARGIN_SUCCESS';
export const LOAD_STOCK_MARGIN_SUCCESS = 'LOAD_STOCK_MARGIN_SUCCESS';
export const CHANGE_STOCK_MARGIN_POSITION = 'CHANGE_STOCK_MARGIN_POSITION';