export const LOAD_MARGIN_SUCCESS = 'LOAD_MARGIN_SUCCESS';
export const LOAD_STOCK_MARGIN_SUCCESS = 'LOAD_STOCK_MARGIN_SUCCESS';
export const CHANGE_STOCK_MARGIN_POSITION = 'CHANGE_STOCK_MARGIN_POSITION';
export const CLICK_MARGIN_BUTTON = 'CLICK_MARGIN_BUTTON';
export const BUTTON_TYPE = {
  ORDER_SELL: 'order_sell',
  ORDER_BUY: 'order_buy',
  SWAP_SELL: 'swap_sell',
  SWAP_BUY: 'swap_buy'
};