export const LOAD_CASH_TRANSFER_SUCCESS = 'LOAD_CASH_TRANSFER_SUCCESS';
export const LOAD_CASH_WITHDRAWAL_SUCCESS = 'LOAD_CASH_WITHDRAWAL_SUCCESS';
export const SAVE_WITHDRAWAL_AMOUNT = 'SAVE_WITHDRAWAL_AMOUNT';