export const LOAD_PHYSICALS_SUCCESS = 'LOAD_PHYSICALS_SUCCESS';
export const LOAD_PHYSICAL_DETAIL_SUCCESS = 'LOAD_PHYSICAL_DETAIL_SUCCESS';
export const LOAD_STOCK_DETAIL_SUCCESS = 'LOAD_STOCK_DETAIL_SUCCESS';
export const SAVE_ORDER_FORM = 'SAVE_ORDER_FORM';
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';