export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_ACCOUNTS_INFO_SUCCESS = 'LOAD_ACCOUNTS_INFO_SUCCESS';
export const GET_DELIVER_STATUS_SUCCESS = 'GET_DELIVER_STATUS_SUCCESS';